### ISSUE TITLE
Failed to parse message text

### ISSUE THREAD

**Issue by avivace** [FruitieX/telegit#1]
POST /github/callback x.x.x.x
received 6327 bytes from x.x.x.x
got push event on REPO-NAME:refs/heads/master from x.x.x.x
Sending to Telegram: [528e6151](https://github.com/user/repo-name/compare/5d6f4d14201f...528e61515ad5): contributor-name, (contributor-email) pushed 1 commit to refs/heads/master: "Create emacs_quicksetup.md"
Unhandled rejection Error: 400 {"ok":false,"error_code":400,"description":"Bad Request: Can't parse message text: Can't find end of the entity starting at byte offset 173"}
    at /home/antuz/github/telegit/node_modules/node-telegram-bot-api/src/telegram.js:136:15
    at tryCatcher (/home/antuz/github/telegit/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/home/antuz/github/telegit/node_modules/bluebird/js/main/promise.js:507:31)
    at Promise._settlePromiseAt (/home/antuz/github/telegit/node_modules/bluebird/js/main/promise.js:581:18)
    at Promise._settlePromises (/home/antuz/github/telegit/node_modules/bluebird/js/main/promise.js:697:14)
    at Async._drainQueue (/home/antuz/github/telegit/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/home/antuz/github/telegit/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate](/home/antuz/github/telegit/node_modules/bluebird/js/main/async.js:15:14)
    at tryOnImmediate (timers.js:543:15)
    at processImmediate [as _immediateCallback](timers.js:523:5)

**Comment by FruitieX** [comment]
Uh, what did you try to send? Is it possible to replicate this?

**Comment by FruitieX** [comment]
Wait, ignore that, I thought this was posted to teleirc project

**Comment by FruitieX** [comment]
Still though, any way to reproduce?

**Comment by FruitieX** [comment]
Hmm, I suspect this happens because Telegram tries to parse the message as markdown, and doesn't find a matching underscore to `emacs_quicksetup.md`...

I'll see if I can escape characters that have special meaning in markdown...

**Comment by avivace** [comment]
Yes, _ is the issue! I've tried pushing different commits with it and they failed in the same manner.

**Comment by FruitieX** [comment]
Thanks, I'm working on this as we speak!

**Comment by FruitieX** [comment]
https://github.com/FruitieX/telegit/commit/14045f32d93408553052a69d7aefa3e298a96bf6 should fix
